services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build: .
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - server/.env
    depends_on:
      - mongo
    volumes:
      - ./server/uploads:/app/uploads
volumes:
  mongo_data:
